Update patch set 3
Patch Set 3:

Regres report:


--- This change breaks 485413 tests: ---
  > dEQP-VK.api.buffer.basic.max_size - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > 485403 more

--- This change alters 440 tests: ---
  > dEQP-VK.api.copy_and_blit.copy_commands2.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.copy_and_blit.core.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.copy_and_blit.dedicated_allocation.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.device_init.create_device_unsupported_features.image2_d_view_of3_d_features_ext - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.info.get_physical_device_properties2.features.image2_d_view_of3_d_features_ext - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthonly_d32_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthonly_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthstencil_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_stencilonly_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_stencilonly_s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > 430 more
          Total tests: 485853
                 Pass: 479976 -> 0 (-479976 -100%)
                 Fail: 440 -> 0 (-440 -100%)
                Crash: 0 -> 485853 (+485853)
        Not Supported: 5437 -> 0 (-5437 -100%)
           Time taken: 30m34.437263183s -> 3m55.726461013s (-87%)

--- Test duration changes ---
  > dEQP-VK.pipeline.monolithic.image.suballocation.sampling_type.combined.view_type.cube_array.format.astc_10x10_srgb_block.count_8.size.13x13_array_of_36: 27.322013252s -> 39.337989ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.vertex_input.multiple_attributes.layout_skip.binding_one_to_many.attributes.float.vec4.mat4: 24.548420966s -> 39.510329ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.image.suballocation.sampling_type.combined.view_type.3d.format.astc_10x8_srgb_block.count_1.size.16x16x16: 22.82233978s -> 37.041338ms (-99%)
  > dEQP-VK.pipeline.monolithic.image.suballocation.sampling_type.combined.view_type.2d_array.format.r32_sint.count_4.size.32x16_array_of_6: 21.609609027s -> 36.10992ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.sampler.border_swizzle.r8_unorm.1gba.transparent_black.gather_0.no_swizzle_hint: 22.867700125s -> 39.158499ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.extended_dynamic_state.after_pipelines.stencil_state_face_front_ge_keep_clear_102_ref_102_depthfail: 21.993479751s -> 38.141009ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.cache.merge.vertex_stage_fragment_stage.src_hit_merged_dst_from_data: 24.67870349s -> 42.899078ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.sampler.view_type.cube.format.r16g16b16a16_sfloat.mag_filter.nearest: 23.208253485s -> 40.439519ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.sampler.view_type.cube_array.format.r32g32b32a32_sint.min_filter.nearest: 21.723442199s -> 38.88866ms (-99%)
  > dEQP-VK.pipeline.monolithic.extended_dynamic_state.two_draws_static.stencil_state_face_both_dual_le_zero_clear_102_ref_103_fail: 20.339612123s -> 37.033778ms (-99%)

Patch-set: 3
Tag: autogenerated:regress