Update patch set 4
Patch Set 4:

Regres report:


--- This change breaks 485413 tests: ---
  > dEQP-VK.api.buffer.basic.max_size - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > 485403 more

--- This change alters 440 tests: ---
  > dEQP-VK.api.copy_and_blit.copy_commands2.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.copy_and_blit.core.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.copy_and_blit.dedicated_allocation.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.device_init.create_device_unsupported_features.image2_d_view_of3_d_features_ext - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.info.get_physical_device_properties2.features.image2_d_view_of3_d_features_ext - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthonly_d32_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthonly_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthstencil_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_stencilonly_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_stencilonly_s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > 430 more
          Total tests: 485853
                 Pass: 479976 -> 0 (-479976 -100%)
                 Fail: 440 -> 0 (-440 -100%)
                Crash: 0 -> 485853 (+485853)
        Not Supported: 5437 -> 0 (-5437 -100%)
           Time taken: 31m7.719694479s -> 3m51.826470029s (-87%)

--- Test duration changes ---
  > dEQP-VK.pipeline.monolithic.extended_dynamic_state.cmd_buffer_start.stencil_state_face_front_xf_inc_clamp_clear_254_ref_255_fail: 24.069535076s -> 38.737688ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.stencil.format.d32_sfloat_s8_uint_separate_layouts.states.fail_wrap.pass_zero.dfail_decc.comp_greater_or_equal: 23.2913258s -> 38.635646ms (-99%)
  > dEQP-VK.pipeline.monolithic.image.suballocation.sampling_type.combined.view_type.3d.format.r8_uint.count_1.size.17x11x5: 25.229341232s -> 43.086398ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.stencil.nocolor.format.s8_uint.states.fail_zero.pass_zero.dfail_decw.comp_not_equal: 22.247624759s -> 38.034739ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.extended_dynamic_state.before_draw.stencil_state_face_back_lt_replace_clear_102_ref_102_fail: 24.690766283s -> 42.354038ms (-99%)
  > dEQP-VK.pipeline.monolithic.extended_dynamic_state.before_draw.stencil_state_face_both_single_gt_inc_clamp_clear_254_ref_254_fail: 24.032004998s -> 41.392079ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.depth.format.d16_unorm.compare_ops.triangle_list_equal_greater_greater_or_equal_not_equal_depth_bounds_test: 21.368456841s -> 36.915049ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.image.suballocation.sampling_type.combined.view_type.2d_array.format.r8g8_snorm.count_1.size.13x13_array_of_6: 21.235488977s -> 36.792608ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.sampler.view_type.2d_array.format.astc_12x12_srgb_block.address_modes.all_mode_clamp_to_border_opaque_black: 23.346930992s -> 41.266329ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.sampler.view_type.2d.format.d32_sfloat_s8_uint.address_modes.uvw_mode_repeat_mode_mirrored_repeat_mode_clamp_to_border: 24.369281905s -> 43.28841ms (-99%)

Patch-set: 4
Tag: autogenerated:regress