Update patch set 1
Patch Set 1:

Regres report:


--- This change breaks 228 tests: ---
  > dEQP-VK.compute.basic.shared_var_multiple_groups - [PASS -> FAIL]
     Comparison failed for Output.values[3]
  > dEQP-VK.compute.basic.shared_var_single_group - [PASS -> FAIL]
     Comparison failed for Output.values[8]
  > dEQP-VK.draw.dynamic_rendering.instanced.draw_indexed_vk_primitive_topology_point_list - [PASS -> FAIL]
  > dEQP-VK.draw.renderpass.instanced.draw_vk_primitive_topology_point_list - [PASS -> FAIL]
  > dEQP-VK.glsl.atomic_operations.add_signed_compute_shared - [PASS -> FAIL]
     ERROR: Result value check failed at index 0. Expected one of the two outcomes: InOut = 0x14062745, Output0 = 0x58c437f8, Output1 = 0x70a26f70, or InOut = 0x14062745, Output0 = 0xfc27efcd, Output1 = 0x58c437f8. Got: InOut = 0x70a26f70, Output0 = 0x58c437f8, Output1 = 0x17de3778. Using Input0 = 0x17de3778 and Input1 = 0xa363b7d5.
  > dEQP-VK.glsl.atomic_operations.add_unsigned_compute_shared - [PASS -> FAIL]
     ERROR: Result value check failed at index 0. Expected one of the two outcomes: InOut = 0x14062745, Output0 = 0x58c437f8, Output1 = 0x70a26f70, or InOut = 0x14062745, Output0 = 0xfc27efcd, Output1 = 0x58c437f8. Got: InOut = 0x70a26f70, Output0 = 0x58c437f8, Output1 = 0x17de3778. Using Input0 = 0x17de3778 and Input1 = 0xa363b7d5.
  > dEQP-VK.glsl.atomic_operations.and_signed_compute_shared - [PASS -> FAIL]
     ERROR: Result value check failed at index 0. Expected one of the two outcomes: InOut = 0x00403750, Output0 = 0x58c437f8, Output1 = 0x10c43778, or InOut = 0x00403750, Output0 = 0x004037d0, Output1 = 0x58c437f8. Got: InOut = 0x10c43778, Output0 = 0x58c437f8, Output1 = 0x17de3778. Using Input0 = 0x17de3778 and Input1 = 0xa363b7d5.
  > dEQP-VK.glsl.atomic_operations.and_unsigned_compute_shared - [PASS -> FAIL]
     ERROR: Result value check failed at index 0. Expected one of the two outcomes: InOut = 0x00403750, Output0 = 0x58c437f8, Output1 = 0x10c43778, or InOut = 0x00403750, Output0 = 0x004037d0, Output1 = 0x58c437f8. Got: InOut = 0x10c43778, Output0 = 0x58c437f8, Output1 = 0x17de3778. Using Input0 = 0x17de3778 and Input1 = 0xa363b7d5.
  > dEQP-VK.glsl.atomic_operations.comp_swap_signed_compute_shared - [PASS -> FAIL]
     ERROR: Result value check failed at index 1. Expected one of the two outcomes: InOut = 0x14963081, Output0 = 0x14963081, Output1 = 0xf32720be, or InOut = 0x14963081, Output0 = 0xf32720be, Output1 = 0xf32720be. Got: InOut = 0x00000000, Output0 = 0x00000000, Output1 = 0x00000000. Using Input0 = 0x7fb251b8 and Input1 = 0x14963081.
  > dEQP-VK.glsl.atomic_operations.comp_swap_unsigned_compute_shared - [PASS -> FAIL]
     ERROR: Result value check failed at index 1. Expected one of the two outcomes: InOut = 0x14963081, Output0 = 0x14963081, Output1 = 0xf32720be, or InOut = 0x14963081, Output0 = 0xf32720be, Output1 = 0xf32720be. Got: InOut = 0x00000000, Output0 = 0x00000000, Output1 = 0x00000000. Using Input0 = 0x7fb251b8 and Input1 = 0x14963081.
  > 218 more

--- This change fixes 18 tests: ---
  > dEQP-VK.draw.dynamic_rendering.instanced.draw_vk_primitive_topology_point_list - [FAIL -> PASS]
  > dEQP-VK.draw.renderpass.instanced.draw_indexed_vk_primitive_topology_point_list - [FAIL -> PASS]
  > dEQP-VK.draw.renderpass.instanced.draw_indirect_vk_primitive_topology_point_list - [FAIL -> PASS]
  > dEQP-VK.glsl.builtin_var.fragdepth.line_list_d32_sfloat - [FAIL -> PASS]
  > dEQP-VK.glsl.builtin_var.fragdepth.point_list_d32_sfloat - [FAIL -> PASS]
  > dEQP-VK.glsl.builtin_var.fragdepth.triangle_list_d32_sfloat - [FAIL -> PASS]
  > dEQP-VK.glsl.builtin_var.fragdepth.triangle_list_d32_sfloat_s8_uint_no_depth_clamp - [FAIL -> PASS]
  > dEQP-VK.glsl.opaque_type_indexing.sampler.const_expression.vertex.sampler2dshadow - [FAIL -> PASS]
  > dEQP-VK.glsl.opaque_type_indexing.sampler.const_literal.vertex.sampler2dshadow - [FAIL -> PASS]
  > dEQP-VK.glsl.opaque_type_indexing.sampler.dynamically_uniform.fragment.sampler2dshadow - [FAIL -> PASS]
  > 8 more
          Total tests: 270115
                 Pass: 268234 -> 268024 (-210)
                 Fail: 1872 -> 2034 (+162 +8%)
              Timeout: 5
      UNIMPLEMENTED(): 1
        UNSUPPORTED(): 1
                Crash: 2 -> 50 (+48 +2400%)
           Time taken: 53m5.45433582s -> 51m57.999946395s (-2%)

--- Test duration changes ---
  > dEQP-VK.pipeline.monolithic.sampler.view_type.1d_array.format.r32_sint.address_modes.uvw_mode_clamp_to_edge_mode_mirrored_repeat_mode_clamp_to_edge: 515.48983ms -> 5.674736996s (+1000%)
  > dEQP-VK.pipeline.monolithic.sampler.view_type.2d_unnormalized.format.r32_sint.address_modes.all_mode_clamp_to_border_custom_0000: 576.068014ms -> 6.341884008s (+1000%)
  > dEQP-VK.pipeline.monolithic.image.suballocation.sampling_type.separate.view_type.1d_array.format.r5g5b5a1_unorm_pack16.count_1.size.2x1_array_of_6: 549.277217ms -> 6.048630188s (+1001%)
  > dEQP-VK.pipeline.monolithic.sampler.view_type.2d.format.e5b9g9r9_ufloat_pack32.address_modes.all_mode_clamp_to_border_custom_0000: 574.467084ms -> 6.337325834s (+1003%)
  > dEQP-VK.pipeline.monolithic.image_view.view_type.1d.format.r32g32b32a32_sint.subresource_range.array_layer_second: 547.342867ms -> 6.055677338s (+1006%)
  > dEQP-VK.pipeline.monolithic.sampler.view_type.cube.format.etc2_r8g8b8a8_srgb_block.mipmap.linear.lod.select_max_4: 533.086787ms -> 5.968229506s (+1019%)
  > dEQP-VK.spirv_assembly.type.vec4.u32.bit_field_s_extract_offset32_count32_vert: 856.57055ms -> 9.87724539s (+1053%)
  > dEQP-VK.pipeline.monolithic.image.suballocation.sampling_type.combined.view_type.3d.format.astc_4x4_srgb_block.count_1.size.1x1x1: 555.987625ms -> 6.507748123s (+1070%)
  > dEQP-VK.spirv_assembly.instruction.compute.signed_int_compare.uint_sgreaterthan: 877.957369ms -> 10.390593446s (+1083%)
  > dEQP-VK.pipeline.monolithic.image.suballocation.sampling_type.combined.view_type.2d.format.astc_12x10_srgb_block.count_1.size.1x1: 559.265775ms -> 6.656970828s (+1090%)

Patch-set: 1
Tag: autogenerated:regress
CC: Gerrit User 7510 <7510@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>