Port LLVM change rL350655
Chromium enabled warning -Wmicrosoft-include which complains the inline line "#include "Windows/WindowsSupport.h""
in lib/Support/Windows/Threading.inc because both are under the same folder (see below error message). The fix was
merged to Clang master at https://reviews.llvm.org/rL350655. Port the change to unblock Windows ARM64 build before
a new rolling of LLVM to swiftshader.

error: #include resolved using non-portable Microsoft search rules as:
../../third_party/swiftshader/third_party/llvm-7.0/llvm/lib/Support/Windows/WindowsSupport.h [-Werror,-Wmicrosoft-include]

Bug: chromium:893460
Change-Id: I9eb32fd92e4d96f7d22a07a7c2da70b98eba19d3