Update patch set 2
Patch Set 2:

Regres report:

          Total tests: 520591
                 Pass: 160795 -> 164051 (+3256 +2%)
                 Fail: 18 -> 110 (+92 +511%)
      UNIMPLEMENTED(): 3
        UNSUPPORTED(): 9
             ASSERT(): 3
                Crash: 9 -> 23 (+14 +155%)
        Not Supported: 359754 -> 356392 (-3362)
           Time taken: 52m16.268346893s -> 52m13.573061588s

--- This change breaks 108 tests: ---
  > dEQP-VK.glsl.atomic_operations.add_signed_vertex - [NOT_SUPPORTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-97f05617de9c99703f08d769049b6dedf73e372b (0x97f05617) starting..
       target implementation = 'X11 EGL'
     Test case 'dEQP-VK.glsl.atomic_operations.add_signed_vertex'..
  > dEQP-VK.glsl.atomic_operations.add_unsigned_vertex - [NOT_SUPPORTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-97f05617de9c99703f08d769049b6dedf73e372b (0x97f05617) starting..
       target implementation = 'X11 EGL'
     Test case 'dEQP-VK.glsl.atomic_operations.add_unsigned_vertex'..
  > dEQP-VK.glsl.atomic_operations.and_signed_vertex - [NOT_SUPPORTED -> FAIL]
     ERROR: Result value check failed at index 0. Expected one of the two outcomes: InOut = 0x00403750, Output0 = 0x58c437f8, Output1 = 0x10c43778, or InOut = 0x00403750, Output0 = 0x004037d0, Output1 = 0x58c437f8. Got: InOut = 0x00000000, Output0 = 0x58c437f8, Output1 = 0x10c43778. Using Input0 = 0x17de3778 and Input1 = 0xa363b7d5.
  > dEQP-VK.glsl.atomic_operations.and_unsigned_vertex - [NOT_SUPPORTED -> FAIL]
     ERROR: Result value check failed at index 0. Expected one of the two outcomes: InOut = 0x00403750, Output0 = 0x58c437f8, Output1 = 0x10c43778, or InOut = 0x00403750, Output0 = 0x004037d0, Output1 = 0x58c437f8. Got: InOut = 0x00000000, Output0 = 0x58c437f8, Output1 = 0x10c43778. Using Input0 = 0x17de3778 and Input1 = 0xa363b7d5.
  > dEQP-VK.glsl.atomic_operations.comp_swap_signed_vertex - [NOT_SUPPORTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-97f05617de9c99703f08d769049b6dedf73e372b (0x97f05617) starting..
       target implementation = 'X11 EGL'
     Test case 'dEQP-VK.glsl.atomic_operations.comp_swap_signed_vertex'..
  > dEQP-VK.glsl.atomic_operations.comp_swap_unsigned_vertex - [NOT_SUPPORTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-97f05617de9c99703f08d769049b6dedf73e372b (0x97f05617) starting..
       target implementation = 'X11 EGL'
     Test case 'dEQP-VK.glsl.atomic_operations.comp_swap_unsigned_vertex'..
  > dEQP-VK.glsl.atomic_operations.exchange_signed_vertex - [NOT_SUPPORTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-97f05617de9c99703f08d769049b6dedf73e372b (0x97f05617) starting..
       target implementation = 'X11 EGL'
     Test case 'dEQP-VK.glsl.atomic_operations.exchange_signed_vertex'..
  > dEQP-VK.glsl.atomic_operations.exchange_unsigned_vertex - [NOT_SUPPORTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-97f05617de9c99703f08d769049b6dedf73e372b (0x97f05617) starting..
       target implementation = 'X11 EGL'
     Test case 'dEQP-VK.glsl.atomic_operations.exchange_unsigned_vertex'..
  > dEQP-VK.glsl.atomic_operations.max_signed_vertex - [NOT_SUPPORTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-97f05617de9c99703f08d769049b6dedf73e372b (0x97f05617) starting..
       target implementation = 'X11 EGL'
     Test case 'dEQP-VK.glsl.atomic_operations.max_signed_vertex'..
  > dEQP-VK.glsl.atomic_operations.max_unsigned_vertex - [NOT_SUPPORTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-97f05617de9c99703f08d769049b6dedf73e372b (0x97f05617) starting..
       target implementation = 'X11 EGL'
     Test case 'dEQP-VK.glsl.atomic_operations.max_unsigned_vertex'..
  > 98 more

--- This change fixes 3261 tests: ---
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.uab.vert.0 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.uab.vert.1 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.uab.vert.2 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.uab.vert.3 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.uab.vert.4 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.uab.vert.5 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.uab.vert.6 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.uab.vert.7 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.uab.vert.8 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.uab.vert.9 - [NOT_SUPPORTED -> PASS]
  > 3251 more

--- Test duration changes ---
  > dEQP-GLES2.functional.flush_finish.wait: 51.052891305s -> 48.06720914s (-5%)
  > dEQP-GLES2.functional.shaders.random.texture.fragment.76: 2.178015909s -> 4.587948448s (+110%)
  > dEQP-GLES2.functional.uniform_api.value.initial.render.array_in_struct.int_ivec4_vertex: 1.976243518s -> 4.243646726s (+114%)
  > dEQP-GLES2.functional.shaders.random.trigonometric.vertex.52: 1.929290354s -> 4.188504774s (+117%)
  > dEQP-GLES2.functional.shaders.preprocessor.basic.null_directive_vertex: 2.012429632s -> 4.430893189s (+120%)
  > dEQP-VK.spirv_assembly.instruction.graphics.spirv_ids_abuse.lots_ids_vert: 1.460081515s -> 7.461560068s (+411%)
  > dEQP-VK.pipeline.stencil.format.d24_unorm_s8_uint.states.fail_inv.pass_repl.dfail_decw.comp_less: 441.241897ms -> 2.511266505s (+469%)

Patch-set: 2
Tag: autogenerated:regress
CC: Gerrit User 7510 <7510@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>