Update patch set 63
Patch Set 63:

Regres report:

          Total tests: 148739
                 Pass: 148738 -> 55270 (-93468 -62%)
                 Fail: 1
                Crash: 0 -> 93468 (+93468)
           Time taken: 14m1.290178505s -> 6m29.41067731s (-53%)

--- This change breaks 93468 tests: ---
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: Resource temporarily unavailable
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: Resource temporarily unavailable
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: Resource temporarily unavailable
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
  > 93458 more

--- This change alters 1 tests: ---
  > dEQP-VK.api.info.android.no_layers - [FAIL -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: Resource temporarily unavailable

--- Test duration changes ---
  > dEQP-VK.memory.pipeline_barrier.host_write_uniform_texel_buffer.1048576: 18.677419526s -> 94.907037ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576: 8.168592942s -> 96.578815ms (-98%)
  > dEQP-VK.ssbo.layout.random.all_shared_buffer.5: 9.578885939s -> 119.606582ms (-98%)
  > dEQP-VK.memory.pipeline_barrier.host_write_storage_buffer.1048576: 6.206965132s -> 89.248546ms (-98%)
  > dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.1048576: 8.015140738s -> 117.490574ms (-98%)
  > dEQP-VK.ubo.random.all_out_of_order_offsets.45: 17.417527072s -> 273.117266ms (-98%)
  > dEQP-VK.memory.pipeline_barrier.host_write_uniform_buffer.8192: 5.042770981s -> 85.505215ms (-98%)
  > dEQP-VK.memory.pipeline_barrier.host_write_uniform_buffer.65536: 5.670048282s -> 102.197739ms (-98%)
  > dEQP-VK.ssbo.layout.random.nested_structs_arrays.0: 5.590121001s -> 104.702847ms (-98%)
  > dEQP-VK.memory.pipeline_barrier.host_write_storage_buffer.8192: 4.516658606s -> 85.149985ms (-98%)

Patch-set: 63
Tag: autogenerated:regress