Update patch set 2
Patch Set 2:

Regres report:


--- This change breaks 485413 tests: ---
  > dEQP-VK.api.buffer.basic.max_size - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > 485403 more

--- This change alters 440 tests: ---
  > dEQP-VK.api.copy_and_blit.copy_commands2.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.copy_and_blit.core.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.copy_and_blit.dedicated_allocation.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.device_init.create_device_unsupported_features.image2_d_view_of3_d_features_ext - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.info.get_physical_device_properties2.features.image2_d_view_of3_d_features_ext - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthonly_d32_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthonly_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthstencil_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_stencilonly_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_stencilonly_s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > 430 more
          Total tests: 485853
                 Pass: 479976 -> 0 (-479976 -100%)
                 Fail: 440 -> 0 (-440 -100%)
                Crash: 0 -> 485853 (+485853)
        Not Supported: 5437 -> 0 (-5437 -100%)
           Time taken: 22m49.627258985s -> 3m58.091036383s (-82%)

--- Test duration changes ---
  > dEQP-VK.pipeline.fast_linked_library.sampler.border_swizzle.r8g8_sint.rgia.opaque_black.gather_1.no_swizzle_hint: 24.654330012s -> 36.883675ms (-99%)
  > dEQP-VK.pipeline.monolithic.image_view.view_type.2d_array.format.astc_5x5_unorm_block.subresource_range.array_size: 24.419667237s -> 37.776035ms (-99%)
  > dEQP-VK.pipeline.monolithic.sampler.view_type.3d.format.eac_r11_snorm_block.address_modes.uvw_mode_clamp_to_edge_mode_clamp_to_edge_mode_clamp_to_border: 23.400374438s -> 37.151185ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.stencil.format.d32_sfloat_s8_uint_separate_layouts.states.fail_keep.pass_decc.dfail_inv.comp_greater: 25.027321243s -> 40.371394ms (-99%)
  > dEQP-VK.pipeline.monolithic.stencil.nocolor.format.d32_sfloat_s8_uint_separate_layouts.states.fail_incc.pass_inv.dfail_wrap.comp_not_equal: 25.3477643s -> 41.193515ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.sampler.view_type.1d_array.format.r16g16_sint.mag_filter.nearest: 24.784943684s -> 41.597956ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.stencil.format.d32_sfloat_s8_uint.states.fail_decw.pass_inv.dfail_keep.comp_not_equal: 23.455483245s -> 39.408995ms (-99%)
  > dEQP-VK.pipeline.monolithic.vertex_input.multiple_attributes.layout_skip.binding_one_to_one.attributes.ivec4.vec3.vec4: 25.273170055s -> 42.911864ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.vertex_input.multiple_attributes.layout_skip.binding_one_to_one.attributes.uvec3.vec4.mat3: 22.298579025s -> 38.072814ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.stencil.format.s8_uint.states.fail_incc.pass_repl.dfail_incc.comp_greater_or_equal: 25.511727479s -> 43.765304ms (-99%)

Patch-set: 2
Tag: autogenerated:regress
CC: Gerrit User 7510 <7510@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>