Update patch set 3
Patch Set 3:

Regres report: 

          Total tests: 182838
                 Pass: 113719 -> 105892 (-7827 -6%)
                 Fail: 92 -> 7243 (+7151 +7772%)
              Timeout: 1
      UNIMPLEMENTED(): 11030
             ASSERT(): 462 -> 369 (-93 -20%)
              ABORT(): 20
                Crash: 112 -> 881 (+769 +686%)
        Not Supported: 57402
           Time taken: 22m16.306436777s -> 22m33.742484664s (+1%)

--- This change breaks 7859 tests: ---
  > dEQP-VK.compute.basic.copy_image_to_ssbo_large - [PASS -> FAIL]
     Comparison failed for Output.values[0]
  > dEQP-VK.compute.basic.copy_image_to_ssbo_small - [PASS -> FAIL]
     Comparison failed for Output.values[0]
  > dEQP-VK.compute.basic.copy_ssbo_multiple_groups - [PASS -> FAIL]
     Comparison failed for Output.values[8]
  > dEQP-VK.compute.basic.copy_ssbo_multiple_invocations - [PASS -> CRASH]
  > dEQP-VK.compute.basic.copy_ssbo_to_image_large - [PASS -> FAIL]
     Comparison failed for pixel 0
  > dEQP-VK.compute.basic.copy_ssbo_to_image_small - [PASS -> FAIL]
     Comparison failed for pixel 1
  > dEQP-VK.compute.basic.image_barrier_multiple - [PASS -> FAIL]
     ERROR: comparison failed, expected 8906752, got 537389056
  > dEQP-VK.compute.basic.ssbo_cmd_barrier_multiple - [PASS -> CRASH]
  > dEQP-VK.compute.basic.ssbo_rw_multiple_groups - [PASS -> FAIL]
     Comparison failed for InOut.values[0]
  > dEQP-VK.compute.basic.ubo_to_ssbo_multiple_groups - [PASS -> FAIL]
     Comparison failed for Output.values[8]
  > 7849 more

--- This change fixes 32 tests: ---
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.1d - [ASSERT -> PASS]
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.1d_array_base_slice - [ASSERT -> PASS]
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.1d_base_mip - [ASSERT -> PASS]
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.1d_base_slice - [ASSERT -> PASS]
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.2d - [ASSERT -> PASS]
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.2d_array_base_slice - [ASSERT -> PASS]
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.2d_base_mip - [ASSERT -> PASS]
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.2d_base_slice - [ASSERT -> PASS]
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.3d - [ASSERT -> PASS]
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.3d_base_mip - [ASSERT -> PASS]
  > 22 more

--- This change alters 77 tests: ---
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.1d_array - [ASSERT -> FAIL]
     Invalid result values
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.1d_array_base_mip - [ASSERT -> FAIL]
     Invalid result values
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.2d_array - [ASSERT -> FAIL]
     Invalid result values
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.2d_array_base_mip - [ASSERT -> FAIL]
     Invalid result values
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.cube - [ASSERT -> FAIL]
     Invalid result values
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.cube_array - [ASSERT -> FAIL]
     Invalid result values
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.cube_array_base_mip - [ASSERT -> FAIL]
     Invalid result values
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.cube_array_base_slice - [ASSERT -> FAIL]
     Invalid result values
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.cube_base_mip - [ASSERT -> FAIL]
     Invalid result values
  > dEQP-VK.binding_model.shader_access.primary_cmd_buf.storage_image.compute.descriptor_array.cube_base_slice - [ASSERT -> FAIL]
     Invalid result values
  > 67 more

Patch-set: 3
Tag: autogenerated:regress