Fix -Wfallthrough,-Werror errors.
Source of most changes is https://reviews.llvm.org/D53950

AArch64ISelLowering.cpp and FunctionComparator.cpp also modified for
failures in building aosp_arm64-eng.

external/swiftshader/third_party/llvm-7.0/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:11002:3: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
  case ISD::GlobalAddress:

external/swiftshader/third_party/llvm-7.0/llvm/lib/Transforms/Utils/FunctionComparator.cpp:414:5: error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]
    LLVM_FALLTHROUGH;

Bug: 124530765
Test: Build aosp_arm64
Change-Id: I851fceaacca5c986ef692e5c1e8f24512e3280bb
(cherry picked from commit 5f3aed75268c21c407db910ea94c2a8840eb7023)