Update patch set 5
Patch Set 5:

Regres report:


--- This change breaks 200965 tests: ---
  > dEQP-VK.api.buffer.basic.size_max_uint64 - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > 200955 more

--- This change alters 36 tests: ---
  > dEQP-VK.api.driver_properties.conformance_version - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.version_check.entry_points - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.graphicsfuzz.spv-stable-quicksort-dontinline - [UNREACHABLE -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     path: <SwiftShader>/build/Linux/.
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.graphicsfuzz.stable-colorgrid-modulo-float-mat-determinant-clamp - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-8010f59c7034804249ecb9d5bfd6cedb9cc3a11c (0x8010f59c) starting..
       target implementation = 'Default'
     libPath: <SwiftShader>/build/Linux/./libvk_swiftshader.so
     [truncated]

Patch-set: 5
Tag: autogenerated:regress