Update patch set 6
Patch Set 6:

Regres report:

          Total tests: 456192
                 Pass: 148738 -> 150893 (+2155 +1%)
                 Fail: 1 -> 85 (+84 +8400%)
                Crash: 0 -> 13 (+13)
        Not Supported: 307453 -> 305201 (-2252)
           Time taken: 45m52.572434608s -> 46m0.669275213s

--- This change breaks 97 tests: ---
  > dEQP-VK.glsl.atomic_operations.add_signed_vertex - [NOT_SUPPORTED -> CRASH]
  > dEQP-VK.glsl.atomic_operations.add_unsigned_vertex - [NOT_SUPPORTED -> CRASH]
  > dEQP-VK.glsl.atomic_operations.and_signed_vertex - [NOT_SUPPORTED -> FAIL]
     ERROR: Result value check failed at index 0. Expected one of the two outcomes: InOut = 0x00403750, Output0 = 0x58c437f8, Output1 = 0x10c43778, or InOut = 0x00403750, Output0 = 0x004037d0, Output1 = 0x58c437f8. Got: InOut = 0x00000000, Output0 = 0x58c437f8, Output1 = 0x10c43778. Using Input0 = 0x17de3778 and Input1 = 0xa363b7d5.
  > dEQP-VK.glsl.atomic_operations.and_unsigned_vertex - [NOT_SUPPORTED -> FAIL]
     ERROR: Result value check failed at index 0. Expected one of the two outcomes: InOut = 0x00403750, Output0 = 0x58c437f8, Output1 = 0x10c43778, or InOut = 0x00403750, Output0 = 0x004037d0, Output1 = 0x58c437f8. Got: InOut = 0x00000000, Output0 = 0x58c437f8, Output1 = 0x10c43778. Using Input0 = 0x17de3778 and Input1 = 0xa363b7d5.
  > dEQP-VK.glsl.atomic_operations.comp_swap_signed_vertex - [NOT_SUPPORTED -> CRASH]
  > dEQP-VK.glsl.atomic_operations.comp_swap_unsigned_vertex - [NOT_SUPPORTED -> CRASH]
  > dEQP-VK.glsl.atomic_operations.exchange_signed_vertex - [NOT_SUPPORTED -> CRASH]
  > dEQP-VK.glsl.atomic_operations.exchange_unsigned_vertex - [NOT_SUPPORTED -> CRASH]
  > dEQP-VK.glsl.atomic_operations.max_signed_vertex - [NOT_SUPPORTED -> CRASH]
  > dEQP-VK.glsl.atomic_operations.max_unsigned_vertex - [NOT_SUPPORTED -> CRASH]
  > 87 more

--- This change fixes 2155 tests: ---
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.vert.0 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.vert.1 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.vert.2 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.vert.3 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.vert.4 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.vert.5 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.vert.6 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.vert.7 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.vert.8 - [NOT_SUPPORTED -> PASS]
  > dEQP-VK.binding_model.descriptorset_random.sets4.constant.ubolimitlow.sbolimitlow.imglimitlow.noiub.vert.9 - [NOT_SUPPORTED -> PASS]
  > 2145 more

--- Test duration changes ---
  > dEQP-GLES2.functional.vertex_arrays.single_attribute.usages.buffer_0_4_short2_vec2_stream_draw_quads_1: 4.218675888s -> 2.08158778s (-50%)
  > dEQP-GLES2.functional.flush_finish.wait: 49.633347744s -> 47.116913566s (-5%)

Patch-set: 6
Tag: autogenerated:regress