Update patch set 2
Patch Set 2:

Breaks sdk_google_phone_armv7-sdk_addon on lmp-emu-dev. Produces errors such as:

third_party/llvm-subzero/include/llvm/ADT/iterator_range.h:63:36: error: no member named 'declval' in namespace 'std'
iterator_range<decltype(begin(std::declval<T>()))> drop_begin(T &&t, int n) {
                              ~~~~~^
third_party/llvm-subzero/include/llvm/ADT/iterator_range.h:64:26: error: no member named 'next' in namespace 'std'
  return make_range(std::next(begin(t), n), end(t));
                    ~~~~~^
third_party/llvm-subzero/build/Android/include/llvm/Support/DataTypes.h:39:10: fatal error: 'cinttypes' file not found
#include <cinttypes>

These might be C++11 features not supported by older Clang versions.

Patch-set: 2
Reviewer: Gerrit User 5005 <5005@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>