IWYU: add cstdint for uintptr_t in llvm-10.0 Signals.h
Upstream commit:

  From ff1681ddb303223973653f7f5f3f3435b48a1983 Mon Sep 17 00:00:00 2001
  From: Sergei Trofimovich <slyich@gmail.com>
  Date: Mon, 23 May 2022 08:03:23 +0100
  Subject: [PATCH] [Support] Add missing <cstdint> header to Signals.h

  Without the change llvm build fails on this week's gcc-13 snapshot as:

    [  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Signals.cpp.o
    In file included from llvm/lib/Support/Signals.cpp:14:
    llvm/include/llvm/Support/Signals.h:119:8: error: variable or field 'CleanupOnSignal' declared void
      119 |   void CleanupOnSignal(uintptr_t Context);
          |        ^~~~~~~~~~~~~~~

Change-Id: Iabe0256d86012e7887e295815aa6cfd50694459a