Update patch set 4
Patch Set 4:

Regres report:

          Total tests: 173645
                 Pass: 173444 -> 55235 (-118209 -68%)
      UNIMPLEMENTED(): 3 -> 0 (-3 -100%)
             ASSERT(): 2 -> 0 (-2 -100%)
                Crash: 196 -> 118410 (+118214 +60313%)
           Time taken: 18m17.597603927s -> 4m48.142178564s (-73%)

--- This change breaks 118209 tests: ---
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > 118199 more

--- This change alters 5 tests: ---
  > dEQP-VK.api.info.get_physical_device_properties2.features - [UNIMPLEMENTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.smoke.triangle_ext_structs - [UNIMPLEMENTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.graphicsfuzz.discard-continue-return - [ASSERT -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.graphicsfuzz.unreachable-continue-statement - [UNIMPLEMENTED -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.spirv_assembly.instruction.compute.hlsl_cases.cbuffer_packing - [ASSERT -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-a7d268a6a3ee9655298d61cdb8b5c42306a4e335 (0xa7d268a6) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168

--- Test duration changes ---
  > dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.1048576: 14.240709168s -> 44.551638ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_bvec4: 12.338915911s -> 44.439945ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_2: 14.370659071s -> 53.602838ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_vec4: 11.234660585s -> 44.959867ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_uvec2: 9.838379373s -> 41.90738ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_ivec4: 11.606849232s -> 50.253275ms (-99%)
  > dEQP-VK.ssbo.layout.random.nested_structs_arrays.17: 8.567838368s -> 43.530597ms (-99%)
  > dEQP-VK.texture.filtering.cube.formats.r16g16b16a16_sfloat.linear_mipmap_linear: 5.716087396s -> 42.780119ms (-99%)
  > dEQP-VK.ubo.random.all_out_of_order_offsets.45: 16.66912644s -> 140.471055ms (-99%)
  > dEQP-VK.texture.filtering.cube.formats.r16g16b16a16_sfloat.nearest_mipmap_nearest: 4.759359521s -> 41.765516ms (-99%)

Patch-set: 4
Tag: autogenerated:regress