Update patch set 1
Patch Set 1:

Regres report:


--- This change breaks 787067 tests: ---
  > dEQP-VK.api.buffer.basic.size_max_uint64 - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > 787057 more

--- This change alters 347 tests: ---
  > dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.1d.astc_10x10_srgb_block.astc_10x10_srgb_block.general_general - [ASSERT -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.1d.astc_10x10_srgb_block.astc_10x10_srgb_block.general_optimal - [ASSERT -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.1d.astc_10x10_srgb_block.astc_10x10_srgb_block.optimal_general - [ASSERT -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.1d.astc_10x10_srgb_block.astc_10x10_srgb_block.optimal_optimal - [ASSERT -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.1d.astc_10x10_unorm_block.astc_10x10_unorm_block.general_general - [ASSERT -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.1d.astc_10x10_unorm_block.astc_10x10_unorm_block.general_optimal - [ASSERT -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.1d.astc_10x10_unorm_block.astc_10x10_unorm_block.optimal_general - [ASSERT -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.1d.astc_10x10_unorm_block.astc_10x10_unorm_block.optimal_optimal - [ASSERT -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.1d.astc_10x5_srgb_block.astc_10x5_srgb_block.general_general - [ASSERT -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > dEQP-VK.api.copy_and_blit.core.image_to_image.all_formats.color.1d.astc_10x5_srgb_block.astc_10x5_srgb_block.general_optimal - [ASSERT -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-41331850eb212df08e010b4d861992fe0aae6222 (0x41331850) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:187
  > 337 more
          Total tests: 842649
                 Pass: 242819 -> 55235 (-187584 -77%)
                 Fail: 18 -> 0 (-18 -100%)
        UNSUPPORTED(): 112 -> 0 (-112 -100%)
             ASSERT(): 217 -> 0 (-217 -100%)
                Crash: 0 -> 787414 (+787414)
        Not Supported: 599483 -> 0 (-599483 -100%)
           Time taken: 3h4m50.727133547s -> 30m56.467932853s (-83%)

--- Test duration changes ---
  > dEQP-VK.ubo.random.all_shared_buffer.48: 37.180429863s -> 80.844666ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_2: 15.418856036s -> 47.932472ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_uniform_buffer.1048576: 19.082618262s -> 74.556427ms (-99%)
  > dEQP-VK.texture.explicit_lod.2d.sizes.128x128_nearest_linear_mipmap_linear_clamp: 10.552801862s -> 42.598014ms (-99%)
  > dEQP-VK.texture.explicit_lod.2d.sizes.128x128_linear_linear_mipmap_linear_clamp: 12.600457893s -> 56.316281ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_uniform_texel_buffer.1048576: 12.573733102s -> 61.60227ms (-99%)
  > dEQP-VK.pipeline.image.suballocation.sampling_type.separate.view_type.cube_array.format.astc_12x12_srgb_block.count_4.size.32x32_array_of_36: 10.234084063s -> 69.923327ms (-99%)
  > dEQP-VK.texture.explicit_lod.2d.sizes.128x128_linear_linear_mipmap_linear_repeat: 12.777841717s -> 87.899808ms (-99%)
  > dEQP-VK.pipeline.image.suballocation.sampling_type.separate.view_type.cube_array.format.astc_12x10_srgb_block.count_4.size.32x32_array_of_36: 8.850292011s -> 69.263541ms (-99%)
  > dEQP-VK.texture.explicit_lod.2d.sizes.128x128_nearest_linear_mipmap_linear_repeat: 10.374036749s -> 82.07078ms (-99%)

Patch-set: 1
Tag: autogenerated:regress
CC: Gerrit User 7510 <7510@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>