Update patch set 1
Patch Set 1:

Regres report:


--- This change breaks 222783 tests: ---
  > dEQP-VK.api.buffer.basic.size_max_uint64 - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > 222773 more

--- This change alters 38 tests: ---
  > dEQP-VK.api.device_init.create_instance_layer_name_abuse - [UNIMPLEMENTED -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.api.driver_properties.conformance_version - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.fragment_operations.early_fragment.discard_early_fragment_tests_stencil - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.glsl.builtin.precision.inverse.highp.mat3 - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.graphicsfuzz.spv-stable-quicksort-dontinline - [UNREACHABLE -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.graphicsfuzz.stable-colorgrid-modulo-float-mat-determinant-clamp - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.graphicsfuzz.stable-mergesort-clamped-conditional-bit-shift - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.graphicsfuzz.stable-quicksort-conditional-bitwise-or-clamp - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.graphicsfuzz.stable-rects-vec4-clamp-conditional-min-mix - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > dEQP-VK.graphicsfuzz.stable-triangle-clamp-conditional-mix - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core git-e2aeccde416b8a07f4d8425f26181130358e3bb2 (0xe2aeccde) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createDevice(physicalDevice, pCreateInfo, pAllocator, &object): VK_ERROR_FEATURE_NOT_PRESENT at vkRefUtilImpl.inl:211
  > 28 more
          Total tests: 222821
                 Pass: 222783 -> 0 (-222783 -100%)
                 Fail: 28 -> 0 (-28 -100%)
      UNIMPLEMENTED(): 1 -> 0 (-1 -100%)
        UNREACHABLE(): 1 -> 0 (-1 -100%)
             ASSERT(): 8 -> 0 (-8 -100%)
                Crash: 0 -> 222821 (+222821)
           Time taken: 31m52.481636751s -> 2m16.779337345s (-92%)

--- Test duration changes ---
  > dEQP-VK.ubo.random.all_shared_buffer.48: 38.523177029s -> 48.628949ms (-99%)
  > dEQP-VK.api.command_buffers.record_many_draws_secondary_2: 31.373004462s -> 41.785448ms (-99%)
  > dEQP-VK.api.command_buffers.record_many_draws_primary_2: 26.971139256s -> 45.465708ms (-99%)
  > dEQP-VK.pipeline.image.suballocation.sampling_type.combined.view_type.cube_array.format.astc_12x12_srgb_block.count_8.size.32x32_array_of_36: 17.708662969s -> 40.209956ms (-99%)
  > dEQP-VK.pipeline.image.suballocation.sampling_type.separate.view_type.cube_array.format.astc_12x12_srgb_block.count_8.size.32x32_array_of_36: 17.652863433s -> 41.579525ms (-99%)
  > dEQP-VK.pipeline.image.suballocation.sampling_type.combined.view_type.cube_array.format.astc_12x12_unorm_block.count_8.size.32x32_array_of_36: 17.606830507s -> 44.234185ms (-99%)
  > dEQP-VK.pipeline.image.suballocation.sampling_type.separate.view_type.cube_array.format.astc_12x10_unorm_block.count_8.size.32x32_array_of_36: 16.225477481s -> 43.511623ms (-99%)
  > dEQP-VK.pipeline.image.suballocation.sampling_type.combined.view_type.cube_array.format.astc_12x10_unorm_block.count_8.size.32x32_array_of_36: 15.720299855s -> 42.164177ms (-99%)
  > dEQP-VK.pipeline.image.suballocation.sampling_type.combined.view_type.cube_array.format.astc_12x10_srgb_block.count_8.size.32x32_array_of_36: 15.485820977s -> 41.614223ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576_vertex_buffer_stride_2: 15.08651258s -> 40.824401ms (-99%)

Patch-set: 1
Tag: autogenerated:regress
CC: Gerrit User 7510 <7510@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>