Regres: Use 'default' dEQP target
Using 'x11_egl' causes a build error on some systems:
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x20): undefined reference to `main'

Change-Id: I07383e1168cc322bb9247ed39db091f91c054b6d