Update patch set 3
Patch Set 3:

Top 17 most common failures:
 • 56777 occurrences: CRASH:
    > Writing test log into /dev/null
    > dEQP Core git-288b9dd96a84b5ed2509c435ad1ca480dd8c7962 (0x288b9dd9) starting..
    >   target implementation = 'Default'
    > FATAL ERROR: Unsupported surface type at tcuLnxX11GlxPlatform.cpp:692
    > 
    Example test: dEQP-GLES2.functional.shaders.random.all_features.fragment.84
 • 92 occurrences: CRASH:
    > Writing test log into /dev/null
    > dEQP Core git-288b9dd96a84b5ed2509c435ad1ca480dd8c7962 (0x288b9dd9) starting..
    >   target implementation = 'Default'
    > Maximum number of clients reachedFATAL ERROR: Unsupported surface type at tcuLnxX11GlxPlatform.cpp:692
    > 
    Example test: dEQP-GLES3.functional.vertex_arrays.single_attribute.usages.dynamic_copy.stride32_short_quads1
 • 14 occurrences: CRASH:
    > Writing test log into /dev/null
    > dEQP Core git-288b9dd96a84b5ed2509c435ad1ca480dd8c7962 (0x288b9dd9) starting..
    >   target implementation = 'Default'
    > Maximum number of clients reachedMaximum number of clients reachedFATAL ERROR: Unsupported surface type at tcuLnxX11GlxPlatform.cpp:692
    > 
    Example test: dEQP-GLES2.functional.fragment_ops.interaction.basic_shader.72
 • 8 occurrences: ASSERT: <SwiftShader>/src/Vulkan/VkImageView.cpp:196 ABORT: ASSERT(imageTypesMatch(image->getImageType()))
    Example test: dEQP-VK.pipeline.no_position.explicit_declarations.basic.multiview.v0
 • 8 occurrences: FAIL: Verification failed
    Example test: dEQP-VK.texture.explicit_lod.2d.sizes.31x55_nearest_linear_mipmap_nearest_repeat
 • 6 occurrences: FAIL: compatibleHandleTypes does not include the host allocation bit at vktMemoryExternalMemoryHostTests.cpp:74
    Example test: dEQP-VK.memory.external_memory_host.bind_image_memory_and_render.with_zero_offset.r8g8b8a8_unorm
 • 4 occurrences: UNSUPPORTED: <SwiftShader>/src/Pipeline/SpirvShader.cpp:754 ABORT: UNSUPPORTED: ReturnValue
    Example test: dEQP-VK.spirv_assembly.instruction.compute.function_control.inline_dont_inline
 • 4 occurrences: UNSUPPORTED: <SwiftShader>/src/Vulkan/libVulkan.cpp:3666 ABORT: UNSUPPORTED: VkPhysicalDeviceLineRasterizationFeaturesEXT::stippled*Lines
    Example test: dEQP-VK.dynamic_state.compute_transfer.single.compute.line_stipple_ext.before
 • 3 occurrences: CRASH:
    > Writing test log into /dev/null
    > dEQP Core git-288b9dd96a84b5ed2509c435ad1ca480dd8c7962 (0x288b9dd9) starting..
    >   target implementation = 'Default'
    > Maximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedFATAL ERROR: Unsupported surface type at tcuLnxX11GlxPlatform.cpp:692
    > 
    Example test: dEQP-GLES2.functional.fragment_ops.depth_stencil.stencil_ops.zero_keep_replace
 • 2 occurrences: FAIL
    Example test: dEQP-VK.graphicsfuzz.stable-rects-vec4-clamp-conditional-min-mix
 • 1 occurrences: FAIL: Wrong driver conformance version (older than used API version
    Example test: dEQP-VK.api.driver_properties.conformance_version
 • 1 occurrences: UNSUPPORTED: <SwiftShader>/src/Device/Context.cpp:41 ABORT: UNSUPPORTED: VkPrimitiveTopology 6
    Example test: dEQP-VK.clipping.clip_volume.depth_clip.line_list_with_adjacency
 • 1 occurrences: TIMEOUT
    Example test: dEQP-VK.synchronization.basic.timeline_semaphore.chain
 • 1 occurrences: UNSUPPORTED: <SwiftShader>/src/Device/Context.cpp:41 ABORT: UNSUPPORTED: VkPrimitiveTopology 8
    Example test: dEQP-VK.clipping.clip_volume.depth_clip.triangle_list_with_adjacency
 • 1 occurrences: UNSUPPORTED: <SwiftShader>/src/Device/Context.cpp:41 ABORT: UNSUPPORTED: VkPrimitiveTopology 7
    Example test: dEQP-VK.clipping.clip_volume.depth_clip.line_strip_with_adjacency
 • 1 occurrences: ASSERT: <SwiftShader>/src/Pipeline/SpirvShader.hpp:199 ABORT: ASSERT(n < wordCount())
    Example test: dEQP-VK.graphicsfuzz.spv-stable-orbit-Os-access-chain-mutate-pointer
 • 1 occurrences: UNSUPPORTED: <SwiftShader>/src/Device/Context.cpp:41 ABORT: UNSUPPORTED: VkPrimitiveTopology 9
    Example test: dEQP-VK.clipping.clip_volume.depth_clip.triangle_strip_with_adjacency

Patch-set: 3
Tag: autogenerated:regress
Attention: {"person_ident":"Gerrit User 7510 \u003c7510@aea13c4a-0b89-3eca-aee9-e193b1b77aa4\u003e","operation":"REMOVE","reason":"removed on reply"}