Update patch set 3
Patch Set 3: Verified-1

Unfortunately this breaks emulator builds:

error: external/swiftshader/Android.bp:90:1: module "swiftshader_host_headers" variant "linux_x86_64": source path external/swiftshader/include-host does not exist

Patch-set: 3
Reviewer: Gerrit User 5005 <5005@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>
Label: Verified=-1