Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> I'm not sure what the Regres problem is. These tests pass locally, both when using the library through the loader or directly. I'm using revision 7b4f9ac of Vulkan-ValidationLayers which is only a couple days old.

Writing test log into TestResults.qpa
dEQP Core git-767dc8b11e6db6a2093ec4d92c8dff6125cef6bc (0x767dc8b1) starting..
  target implementation = 'X11 EGL'
Xlib:  extension "NV-GLX" missing on display ":20".
FATAL ERROR: vk.enumeratePhysicalDevices(instance, &numDevices, DE_NULL): VK_ERROR_INITIALIZATION_FAILED at vkQueryUtil.cpp:80
Killed

Probably something to do with how dEQP is linked for me.

Patch-set: 3
Reviewer: Gerrit User 7183 <7183@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>