Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4:
> > 
> > > Patch Set 4: Presubmit-Ready+1
> > > 
> > > Not sure why RegressionBot failed to build while kokoro passed all tests. Trying again.
> > 
> > third_party/SPIRV-Tools/source/val/validate_builtins.cpp:2935:10: error: enumeration value ‘SpvBuiltInRayGeometryIndexKHR’ not handled in switch [-Werror=switch]
> >  2935 |   switch (label) {
> >       |          ^
> 
> Thanks for the info!

Although, this isn't in our code, this is in third_party code. Any way RegressionBot could not treat third_party code warnings as errors?

Patch-set: 4
Reviewer: Gerrit User 5050 <5050@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>