Update patch set 4
Patch Set 4: -Presubmit-Ready

> Patch Set 4: Presubmit-Ready+1
> 
> (1 comment)
> 
> Sorry about that.

Seeing these errors now, maybe some weird interaction with the Debug.hpp header being added to RecursiveLock.hpp to support ASSERT.

swiftshader\src\opengl\libegl\main.cpp(73): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers

Sorry about the spam, I don't have a windows machine handy and it seems like the windows build is pretty important so just running it through kokoro.

Patch-set: 4
Reviewer: Gerrit User 7153 <7153@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>
Label: Presubmit-Ready=0