Update patch set 6
Patch Set 6:

Regres report:


--- This change breaks 485413 tests: ---
  > dEQP-VK.api.buffer.basic.max_size - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > 485403 more

--- This change alters 440 tests: ---
  > dEQP-VK.api.copy_and_blit.copy_commands2.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.copy_and_blit.core.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.copy_and_blit.dedicated_allocation.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.device_init.create_device_unsupported_features.image2_d_view_of3_d_features_ext - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.info.get_physical_device_properties2.features.image2_d_view_of3_d_features_ext - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthonly_d32_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthonly_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthstencil_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_stencilonly_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_stencilonly_s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > 430 more
          Total tests: 485853
                 Pass: 479976 -> 0 (-479976 -100%)
                 Fail: 440 -> 0 (-440 -100%)
                Crash: 0 -> 485853 (+485853)
        Not Supported: 5437 -> 0 (-5437 -100%)
           Time taken: 34m28.617911476s -> 3m57.168239502s (-88%)

--- Test duration changes ---
  > dEQP-VK.pipeline.pipeline_library.sampler.border_swizzle.r32g32_uint.argb.opaque_white.gather_1.no_swizzle_hint: 23.221545428s -> 36.092989ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.image.suballocation.sampling_type.separate.view_type.2d_array.format.astc_4x4_srgb_block.count_1.size.32x16_array_of_3: 22.610325307s -> 35.165448ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.sampler.view_type.2d_array.format.r16g16b16a16_sfloat.mipmap.linear.lod.select_bias_2_5: 25.710894181s -> 42.678698ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.stencil.nocolor.format.d32_sfloat_s8_uint_separate_layouts.states.fail_keep.pass_inv.dfail_inv.comp_greater: 24.884649397s -> 42.114588ms (-99%)
  > dEQP-VK.texture.explicit_lod.2d.sizes.128x128_nearest_linear_mipmap_linear_clamp: 32.902710479s -> 57.826508ms (-99%)
  > dEQP-VK.pipeline.monolithic.image.suballocation.sampling_type.combined.view_type.1d_array.format.r8g8b8a8_snorm.count_8.size.512x1_array_of_6: 22.460103959s -> 39.556919ms (-99%)
  > dEQP-VK.pipeline.monolithic.vertex_input.multiple_attributes.out_of_order.binding_one_to_many.attributes_sequential.ivec3.uvec4.float: 22.523205449s -> 40.331769ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.image.suballocation.sampling_type.separate.view_type.cube_array.format.astc_10x8_unorm_block.count_8.size.13x13_array_of_36: 25.383242149s -> 45.611429ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.sampler.view_type.3d.format.a2r10g10b10_uint_pack32.mipmap.nearest.lod.select_min_1: 23.404669619s -> 42.905549ms (-99%)
  > dEQP-VK.pipeline.pipeline_library.extended_dynamic_state.cmd_buffer_start.stencil_state_face_both_dual_ge_dec_wrap_clear_0_ref_0_depthfail: 22.281038994s -> 41.105288ms (-99%)

Patch-set: 6
Tag: autogenerated:regress