Update patch set 2
Patch Set 2: Verified+1

Slightly ironic that the Kokoro failure is due to a macos timeout:

  ERROR: Aborting VM command due to timeout of 10800 seconds

Given that this file is only accessed by Regres, there is no way this could have affected the Kokoro build. Submitting.

Patch-set: 2
Reviewer: Gerrit User 7183 <7183@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>
Label: Verified=+1