Ignore two unused variables in llvm
... to allow rolling SwiftShader for Android.

external/swiftshader/third_party/llvm-10.0/llvm/lib/Support/
ManagedStatic.cpp:21:30: error: unused variable 'ManagedStaticMutex'

external/swiftshader/third_party/llvm-10.0/llvm/lib/Support/
ManagedStatic.cpp:22:24: error: unused variable 'mutex_init_flag'

Bug: b/171498948
Test: build inside Android repo
Change-Id: Idc3ab2ef4de759c14499454f5d841b750124686b