Update patch set 18
Patch Set 18:

Compile error after fixing conflicts:

/Users/lfy/SwiftShader/src/OpenGL/common/Image.cpp:1757:7: error: use of undeclared identifier
      'LoadImageData'; did you mean 'loadImageData'?
                                                LoadImageData<RGB9E5>(xoffset, yoffset, zoffs...
                                                ^~~~~~~~~~~~~

Patch-set: 18
Reviewer: Gerrit User 5545 <5545@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>