Update patch set 5
Patch Set 5:

Regres report:

          Total tests: 186230
                 Pass: 186230 -> 55235 (-130995 -70%)
                Crash: 0 -> 130995 (+130995)
           Time taken: 19m53.650772338s -> 4m53.721749707s (-75%)

--- This change breaks 130995 tests: ---
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > 130985 more

--- Test duration changes ---
  > dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.1048576: 14.384301528s -> 46.384251ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_bvec4: 12.8750338s -> 41.668773ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_ivec4: 11.593915177s -> 40.870544ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_bvec3: 11.523404154s -> 41.277331ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_storage_buffer.1048576: 11.383520925s -> 42.937326ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_bvec2: 10.640036559s -> 40.83502ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_float: 8.916503325s -> 42.378054ms (-99%)
  > dEQP-VK.spirv_assembly.instruction.compute.spirv_ids_abuse.lots_ids: 7.461554439s -> 39.596867ms (-99%)
  > dEQP-VK.spirv_assembly.instruction.graphics.spirv_ids_abuse.lots_ids_frag: 7.662011224s -> 47.99285ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_uniform_texel_buffer.65536: 6.103773702s -> 45.786632ms (-99%)

Patch-set: 5
Tag: autogenerated:regress