Update patch set 11
Patch Set 11:

The Kokoro build issue appears to be with marl::blocking_call:

    In file included from /SwiftShader/src/Vulkan/VkSemaphore.cpp:25:0:
    /SwiftShader/third_party/marl/include/marl/blockingcall.h: In lambda function:
    /SwiftShader/third_party/marl/include/marl/blockingcall.h:33:18: error: parameter packs not expanded with ‘...’:
        result = f(args...);
                    ^
    /SwiftShader/third_party/marl/include/marl/blockingcall.h:33:18: note:         ‘args’
    /SwiftShader/third_party/marl/include/marl/blockingcall.h:33:22: error: expansion pattern ‘args’ contains no argument packs
        result = f(args...);
                        ^
    /SwiftShader/third_party/marl/include/marl/blockingcall.h: In lambda function:
    /SwiftShader/third_party/marl/include/marl/blockingcall.h:49:9: error: parameter packs not expanded with ‘...’:
        f(args...);
            ^
    /SwiftShader/third_party/marl/include/marl/blockingcall.h:49:9: note:         ‘args’
    /SwiftShader/third_party/marl/include/marl/blockingcall.h:49:13: error: expansion pattern ‘args’ contains no argument packs
        f(args...);
                ^
    /SwiftShader/third_party/marl/include/marl/blockingcall.h: In instantiation of ‘struct marl::detail::OnNewThread<void>::call(F&&, Args&& ...) [with F = vk::Semaphore::Impl::wait()::__lambda5; Args = {}]::__lambda3’:
    /SwiftShader/third_party/marl/include/marl/blockingcall.h:50:6:   required from ‘static void marl::detail::OnNewThread<void>::call(F&&, Args&& ...) [with F = vk::Semaphore::Impl::wait()::__lambda5; Args = {}]’
    /SwiftShader/third_party/marl/include/marl/blockingcall.h:77:54:   required from ‘decltype (f(marl::blocking_call::args ...)) marl::blocking_call(F&&, Args&& ...) [with F = vk::Semaphore::Impl::wait()::__lambda5; Args = {}; decltype (f(marl::blocking_call::args ...)) = void]’
    /SwiftShader/src/Vulkan/VkSemaphore.cpp:115:5:   required from here
    /SwiftShader/third_party/marl/include/marl/blockingcall.h:49:9: error: using invalid field ‘marl::detail::OnNewThread<void>::call(F&&, Args&& ...)::__lambda3::__args’
        f(args...);

I'll look into this.

Patch-set: 11
Reviewer: Gerrit User 7183 <7183@aea13c4a-0b89-3eca-aee9-e193b1b77aa4>