Update patch set 7
Patch Set 7:

Regres report:

          Total tests: 186246
                 Pass: 186246 -> 55235 (-131011 -70%)
                Crash: 0 -> 131011 (+131011)
           Time taken: 20m18.647926667s -> 5m0.220434496s (-75%)

--- This change breaks 131011 tests: ---
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > 131001 more

--- Test duration changes ---
  > dEQP-VK.ubo.random.all_out_of_order_offsets.45: 16.754519413s -> 46.744204ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.1048576: 14.630368423s -> 46.903009ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_storage_buffer.1048576: 11.817405031s -> 39.761721ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_bvec4: 12.63926781s -> 46.938051ms (-99%)
  > dEQP-VK.texture.shadow.cube.linear.greater_d32_sfloat_s8_uint: 4.336282658s -> 16.510824ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_bvec2: 10.705146838s -> 44.04612ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_ivec4: 11.491739511s -> 53.370553ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_uvec2: 10.057087894s -> 46.767485ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_uint: 9.261986656s -> 46.838496ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_int: 9.137824134s -> 49.002191ms (-99%)

Patch-set: 7
Tag: autogenerated:regress