Update patch set 6
Patch Set 6:

Regres report:

          Total tests: 186246
                 Pass: 186246 -> 55235 (-131011 -70%)
                Crash: 0 -> 131011 (+131011)
           Time taken: 19m57.904436358s -> 4m50.166576872s (-75%)

--- This change breaks 131011 tests: ---
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-da1463790952d1c1ac6c1409d814c29286da1aea (0xda146379) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INITIALIZATION_FAILED at vkRefUtilImpl.inl:168
  > 131001 more

--- Test duration changes ---
  > dEQP-VK.ubo.random.all_out_of_order_offsets.45: 16.567221471s -> 47.044333ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_index_buffer.1048576: 13.163264033s -> 39.808077ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_bvec4: 12.756603194s -> 41.709209ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_ivec4: 11.975172916s -> 40.402262ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_storage_buffer.1048576: 11.850821603s -> 41.801555ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_bvec2: 10.836661789s -> 41.706151ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_uint: 9.041477205s -> 40.936682ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_uvec2: 9.838293086s -> 45.350471ms (-99%)
  > dEQP-VK.subgroups.ballot_broadcast.compute.subgroupbroadcast_int: 8.941624307s -> 42.512207ms (-99%)
  > dEQP-VK.texture.shadow.cube.nearest_mipmap_nearest.always_d32_sfloat: 3.545898746s -> 17.413654ms (-99%)

Patch-set: 6
Tag: autogenerated:regress