Update patch set 7
Patch Set 7:

Regres report:


--- This change breaks 485413 tests: ---
  > dEQP-VK.api.buffer.basic.max_size - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > 485403 more

--- This change alters 440 tests: ---
  > dEQP-VK.api.copy_and_blit.copy_commands2.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.copy_and_blit.core.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.copy_and_blit.dedicated_allocation.image_to_image.simple_tests.whole_image_diff_fromat - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.device_init.create_device_unsupported_features.image2_d_view_of3_d_features_ext - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.api.info.get_physical_device_properties2.features.image2_d_view_of3_d_features_ext - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthonly_d32_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthonly_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_depthstencil_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_stencilonly_d32s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > dEQP-VK.dynamic_rendering.partial_secondary_cmd_buff.suballocation.unused_clear_attachments.colorunused_colorunused_colorunused_colorunused_stencilonly_s8_unused - [FAIL -> CRASH]
     Writing test log into /dev/null
     dEQP Core e7b180ad536663d73692d000bcddb5f34f0a8d1d (0xe7b180ad) starting..
       target implementation = 'Default'
     FATAL ERROR: vk.createInstance(pCreateInfo, pAllocator, &object): VK_ERROR_INCOMPATIBLE_DRIVER at vkRefUtilImpl.inl:230
  > 430 more
          Total tests: 485853
                 Pass: 479976 -> 0 (-479976 -100%)
                 Fail: 440 -> 0 (-440 -100%)
                Crash: 0 -> 485853 (+485853)
        Not Supported: 5437 -> 0 (-5437 -100%)
           Time taken: 35m43.925386181s -> 3m54.986906859s (-89%)

--- Test duration changes ---
  > dEQP-VK.spirv_assembly.instruction.graphics.float_controls.fp32.generated_args.nan_add_var_preserve_vert: 27.627053645s -> 42.231197ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.sampler.border_swizzle.r32g32b32a32_uint.rg0a.transparent_black.gather_2.no_swizzle_hint: 22.998443948s -> 36.851517ms (-99%)
  > dEQP-VK.pipeline.monolithic.render_to_image.core.2d.small.a2b10g10r10_unorm_pack32_s8_uint: 21.695757305s -> 36.815338ms (-99%)
  > dEQP-VK.pipeline.monolithic.sampler.view_type.1d.format.r16g16b16a16_sfloat.address_modes.uvw_mode_clamp_to_edge_mode_clamp_to_border_mode_repeat: 18.255334734s -> 31.169059ms (-99%)
  > dEQP-VK.pipeline.monolithic.extended_dynamic_state.before_draw.stencil_state_face_back_ge_dec_clamp_clear_1_ref_2_depthfail: 23.237954717s -> 39.735508ms (-99%)
  > dEQP-VK.pipeline.monolithic.depth.nocolor.format.d32_sfloat.compare_ops.triangle_list_greater_always_less_not_equal: 20.555243963s -> 35.154518ms (-99%)
  > dEQP-VK.pipeline.monolithic.sampler.border_swizzle.r8_snorm.igba.transparent_black.gather_3.no_swizzle_hint: 20.440264582s -> 35.342348ms (-99%)
  > dEQP-VK.pipeline.fast_linked_library.sampler.view_type.3d.format.r16_sfloat.address_modes.uvw_mode_mirror_clamp_to_edge_mode_repeat_mode_clamp_to_edge: 22.289478658s -> 38.721227ms (-99%)
  > dEQP-VK.pipeline.monolithic.image.suballocation.sampling_type.combined.view_type.cube_array.format.r8_uint.count_4.size.13x13_array_of_36: 22.896988889s -> 40.526147ms (-99%)
  > dEQP-VK.pipeline.monolithic.render_to_image.core.cube_array.mipmap.a1r5g5b5_unorm_pack16_s8_uint: 22.740719004s -> 40.302677ms (-99%)

Patch-set: 7
Tag: autogenerated:regress