[fuchsia] Fix Fuchsia build of swiftshader_vulkan_unittests
When building the vulkan library (libvk_swiftshader.so) for Fuchsia,
do not place the stripped binary to $OUT_DIR/swiftshader/ instead of
its default location (i.e. $OUT_DIR/lib/).

That's because the Fuchsia packaging scripts rely on the location
of the unstripped library ($OUT+DIR/lib.unstripped/) to find the
release one (i.e. by replacing 'lib.unstripped' with 'lib').

This resulted in a build error that looks like [1]. This CL works
around the issue rather than fixing the scripts.

Bug: NONE

Change-Id: Ida846cdc5da7af932ee3ce466809bcea73d6a65e

[1] ------------------- build error output ---------------------------
FAILED: gen/third_party/swiftshader/tests/VulkanUnitTests/swiftshader_vulkan_unittests/swiftshader_vulkan_unittests.archive_manifest gen/third_party/swiftshader/tests/VulkanUnitTests/swiftshader_vulkan_unittests/ids.txt gen/third_party/swiftshader/tests/VulkanUnitTests/swiftshader_vulkan_unittests/swiftshader_vulkan_unittests.cmx
python ../../build/config/fuchsia/prepare_package_inputs.py --root-dir ../../ --out-dir . --app-name swiftshader_vulkan_unittests --app-filename swiftshader_vulkan_unittests__exec --manifest-input-path ../../build/config/fuchsia/tests.cmx --runtime-deps-file gen/third_party/swiftshader/tests/VulkanUnitTests/swiftshader_vulkan_unittests/swiftshader_vulkan_unittests.runtime_deps --depfile-path gen/third_party/swiftshader/tests/VulkanUnitTests/swiftshader_vulkan_unittests__write_manifest_stamp.d --manifest-path gen/third_party/swiftshader/tests/VulkanUnitTests/swiftshader_vulkan_unittests/swiftshader_vulkan_unittests.archive_manifest --build-ids-file gen/third_party/swiftshader/tests/VulkanUnitTests/swiftshader_vulkan_unittests/ids.txt
Traceback (most recent call last):
  File "../../build/config/fuchsia/prepare_package_inputs.py", line 193, in <module>
    sys.exit(main())
  File "../../build/config/fuchsia/prepare_package_inputs.py", line 190, in main
    return BuildManifest(args)
  File "../../build/config/fuchsia/prepare_package_inputs.py", line 163, in BuildManifest
    _WriteBuildIdsTxt(binaries, args.build_ids_file)
  File "../../build/config/fuchsia/prepare_package_inputs.py", line 82, in _WriteBuildIdsTxt
    info = elfinfo.get_elf_info(_GetStrippedPath(binary_path))
  File "/work/cr-swiftshader/src/build/config/fuchsia/elfinfo.py", line 407, in get_elf_info
    with mmapper(filename) as mapped:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/work/cr-swiftshader/src/build/config/fuchsia/elfinfo.py", line 252, in mmapper
    fileobj = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: './lib/libvk_swiftshader.so'
ninja: build stopped: subcommand failed.

Change-Id: I4137c9edbdc04b3b35a8a43e3f37b9e64fe5b1d7