Default to use llvm16 for riscv64
Because cross-compiling chromium failed with the following error when using llvm 10:

../../third_party/swiftshader/src/Reactor/LLVMJIT.cpp:796:83: error: no member named 'Create' in 'llvm::jitlink::InProcessMemoryManager'
  796 |             , objectLayer(session, llvm::cantFail(llvm::jitlink::InProcessMemoryManager::Create()))
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated

Change-Id: Ideb0c987dad35ca06b247e18ded6398f313921de