Target macOS 10.12 when building LLVM
When enabling C++17, LLVM uses std::shared_mutex instead of its own
implementation. On macOS it requires version 10.12 (Sierra), while
Chrome must still support 10.11. However, we don't need LLVM as Reactor
backend, except for ARM64, but Mac devices with such CPU have a more
recent OS version.

llvm-10.0/llvm/include/llvm/Support/RWMutex.h:100:8: error: 'shared_mutex' is unavailable: introduced in macOS 10.12

Bug: b/174843857
Change-Id: Ie24095aa17d22072cfb9d655b87252cbea5209d0