Update patch set 65
Patch Set 65:

Regres report:

          Total tests: 148739
                 Pass: 148738 -> 55284 (-93454 -62%)
                 Fail: 1 -> 2 (+1 +100%)
                Crash: 0 -> 93453 (+93453)
           Time taken: 14m1.290178505s -> 6m30.241682216s (-53%)

--- This change breaks 93454 tests: ---
  > dEQP-VK.api.buffer.dedicated_alloc.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
     LLVM ERROR: out of memory
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
     LLVM ERROR: out of memory
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: Resource temporarily unavailable
  > dEQP-VK.api.buffer.dedicated_alloc.storage.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: Resource temporarily unavailable
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     LLVM ERROR: out of memory
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: Resource temporarily unavailable
  > dEQP-VK.api.buffer.dedicated_alloc.storage.index.vertex.indirect.create.zero - [PASS -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: Resource temporarily unavailable
  > 93444 more

--- This change alters 1 tests: ---
  > dEQP-VK.api.info.android.no_layers - [FAIL -> CRASH]
     Writing test log into TestResults.qpa
     dEQP Core git-c795f792eee0d53cb2fd73c242203c16f7226bec (0xc795f792) starting..
       target implementation = 'X11 EGL'
     FATAL ERROR: Resource temporarily unavailable

--- Test duration changes ---
  > dEQP-VK.memory.pipeline_barrier.host_write_uniform_texel_buffer.1048576: 18.677419526s -> 92.747261ms (-99%)
  > dEQP-VK.ssbo.layout.random.all_shared_buffer.5: 9.578885939s -> 79.324708ms (-99%)
  > dEQP-VK.memory.pipeline_barrier.host_write_vertex_buffer.1048576: 8.168592942s -> 101.471824ms (-98%)
  > dEQP-VK.pipeline.image.suballocation.sampling_type.separate.view_type.cube.format.r16g16b16a16_sfloat.count_1.size.32x32: 2.326544836s -> 31.550485ms (-98%)
  > dEQP-VK.memory.pipeline_barrier.host_write_storage_buffer.1048576: 6.206965132s -> 91.713808ms (-98%)
  > dEQP-VK.memory.pipeline_barrier.host_write_uniform_buffer.65536: 5.670048282s -> 84.874571ms (-98%)
  > dEQP-VK.memory.pipeline_barrier.host_write_uniform_texel_buffer.8192: 4.888905749s -> 84.016372ms (-98%)
  > dEQP-VK.ssbo.layout.random.nested_structs_arrays.0: 5.590121001s -> 96.249322ms (-98%)
  > dEQP-VK.memory.pipeline_barrier.host_write_uniform_buffer.8192: 5.042770981s -> 90.826425ms (-98%)
  > dEQP-VK.ubo.random.all_out_of_order_offsets.45: 17.417527072s -> 316.789324ms (-98%)

Patch-set: 65
Tag: autogenerated:regress